#spring??
spring:
  #1.????
  application:
    name: Absence #?????
  #2.??????
  datasource:
    workflow:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/workflow?useUnicode=true&characterEncoding=utf8
      username : root
      password : root
    test:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
      username: root
      password: root

  activiti:
    history-level: full
    db-history-used: true
  # 添加统一的servlet的访问路径，在tomcat的路径之后拼接
  mvc:
    servlet:
      path: /v1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#????
server:
  port: 9009
  # 配置tomcat的绝对路径
  servlet:
    context-path: /absence

logging:
  level:
    root: info
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
